### ISSUE TITLE
Run docker in rundeck-docker

### ISSUE THREAD

**Issue by mcortinas** [rundeck-plugins/docker#3]
Hello, 

 I'm just testing run a docker inside a rundeck-docker with your plugin.
 I can install the pluguin but the hello work job with docker plugin fail.
 Let me share the environment:

 I launch the https://github.com/jjethwa/rundeck docker image with this command

1. Run rundeck in a docker
```
sudo docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock -p 4440:4440 -e SERVER_URL=http://MY.HOSTNAME.COM:4440 --name rundeck jjethwa/rundeck
```
2. Attach to docker and install the docker plugin
[hello world.yaml.txt](https://github.com/rundeck-plugins/docker/files/1081342/hello.world.yaml.txt)

3. Create a basic project + job with 1 docker run step with a basic hello world. it fails.
I attached the log
[hello world-20170616-155848.txt](https://github.com/rundeck-plugins/docker/files/1081339/hello.world-20170616-155848.txt)

But, for other way I check run dockeer in docker: :+1: 
```
root@1b2e44d51614:/# docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

Could you help me what i'm doing wrong???

**Comment by mcortinas** [comment]
Let me attach another log output with debug loglevel.
[hello world-20170616-161416.txt](https://github.com/rundeck-plugins/docker/files/1081361/hello.world-20170616-161416.txt)

**Comment by ahonor** [comment]
@mcortinas I have not tried this from a rundeck hosted in a container too. How have you configured the plugin?

**Comment by mcortinas** [comment]
I don't configured the plugin, i just installed.
```
zip -r docker-container.zip docker-container
cp docker-container.zip $RDECK_BASE/libext
```

**Comment by ahonor** [comment]
Can you show you configured the step in your job?

**Comment by mcortinas** [comment]
Sure! 
[hello world.yaml.txt](https://github.com/rundeck-plugins/docker/files/1081342/hello.world.yaml.txt)

**Comment by mcortinas** [comment]
Let me share the environment:
```
root@41ccc4a701c6:/tmp/docker-master# uname -a
Linux 41ccc4a701c6 4.11.4-200.fc25.x86_64 #1 SMP Wed Jun 7 18:28:00 UTC 2017 x86_64 GNU/Linux
root@41ccc4a701c6:/tmp/docker-master# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:18:37 2017
 OS/Arch:      linux/amd64
 Experimental: true
root@41ccc4a701c6:/tmp/docker-master# python --version
Python 2.7.9
```

**Comment by ahonor** [comment]
Does the docker image where rundeck is hosted contain the docker CLI? Can you get a bash shell in the container and try running some commands like `docker ps` to check if you see your other container running?

**Comment by mcortinas** [comment]
Yes, the first continer where rundeck is hosted is launched with parameters ``` --privileged -v /var/run/docker.sock:/var/run/docker.sock ``` in order to share the docker-server. (pasted the output in my first comment)

I also installed docker-engine (client) inside the container, where the rundeck is hosted. I can run docker run hello-world inside the docker (pasted the output in my first comment). I can run docker ps, docker run, docker image, etc without problems.

Do you know some action in order to see more traces (debug loglevel) in the python script where docker run is launced?

**Comment by mcortinas** [comment]
any idea?

**Comment by ltamaster** [comment]
Hi @mcortinas 
I reproduced and fixed the error.
My problem was that rundeck user didn't have permissions to /var/run/docker.sock

<img width="1414" alt="screenshot 2017-07-06 12 11 24" src="https://user-images.githubusercontent.com/6034968/27921008-6cb12bae-6244-11e7-8842-ad713209ae55.png">


So I added the rundeck user to the group that has permissions to  /var/run/docker.sock (check it with ls) and then I restarted rundeck.

For example:
```
root@9ffa1c5cf1e3:/# ls -l /var/run/docker.sock 
srw-rw---- 1 root staff 0 Jul  6 13:10 /var/run/docker.sock
root@9ffa1c5cf1e3:/# usermod -a -G staff rundeck
root@9ffa1c5cf1e3:/# service rundeckd restart

```
<img width="1435" alt="screenshot 2017-07-06 12 16 11" src="https://user-images.githubusercontent.com/6034968/27921174-ef062258-6244-11e7-9cdc-3dff38389256.png">


<img width="1438" alt="screenshot 2017-07-06 12 12 36" src="https://user-images.githubusercontent.com/6034968/27921009-6cb3fa96-6244-11e7-9387-a28e6f851ec3.png">

Luis

**Comment by djeeg** [comment]
I'm trying to get rundeck talking to docker though this pluging using jordan's image without:
 - customising the image
 - bashing into the container

@mcortinas mentioned
> I also installed docker-engine (client) inside the container

I think I can get around this by binding the host client runtime (as well as the socket)

```
  rundeck:
    image: jordan/rundeck:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #careful security
      #- /usr/bin/docker:/usr/bin/docker #azure
      - /usr/local/bin/docker:/usr/local/bin/docker #boot2docker
```
	  
	  
I couldnt get @ltamaster exact solution to work, had to tweak it a little bit using info from these:
http://vitorbaptista.com/how-to-access-hosts-docker-socket-without-root
https://github.com/jenkinsci/docker/issues/263#issuecomment-218132981

```
DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
groupadd -for -g ${DOCKER_GID} docker
usermod -aG docker rundeck
service rundeckd restart
```

Still need to figure out the best way to run those commands in CI/CD environment.

Hope this helps someone

**Comment by vwoloszyn** [comment]
HI @djeeg , It helped me :) thanks!
