### ISSUE TITLE
docker folder not found - Also, I had to compile using gradlew

### ISSUE THREAD

**Issue by JoeJenningsDMC** [rundeck-plugins/docker#42]
When I compiled this project into a zip archive and put it into my libext directory. I was getting errors that a 'docker' directory wasn't present. I had to manually put all the source of the zip archive into a directory called 'docker' and archive this directory into a new zip file to get it to work.

I'm using Rundeck 3.0.23-20190619.

Also, the readme says that you should use `gradle build` to compile the plugin. This kept failing after 20 or so seconds and I had to use `gradlew` instead.

**Comment by ltamaster** [comment]
Hi @JoeJenningsDMC 

You can download the plugin from the release link 
https://github.com/rundeck-plugins/docker/releases/download/1.4.1/docker-container-1.4.1.zip

Thanks
Luis
