### ISSUE TITLE
Exception during installation

### ISSUE THREAD

**Issue by pmizwa** [rundeck-plugins/docker#43]
AILURE: Build failed with an exception.

* Where:
Script 'https://raw.githubusercontent.com/rundeck-plugins/build-zip/master/build.gradle' line: 74

* What went wrong:
A problem occurred evaluating script.
> Could not find method leftShift() for arguments [build_5euplq0w1agkutluqphlqsf3j$_run_closure4@345c8365] on task ':build' of type org.gradle.api.DefaultTask.

**Comment by ltamaster** [comment]
Hi @pmizwa 

Did you try with `./gradlew build` ?

Luis
