### ISSUE TITLE
The official rundeck docker image doesn't include python environment.

### ISSUE THREAD

**Issue by endu** [rundeck-plugins/docker#44]
This plugin requires python environment. But the official rundeck docker image doesn't include python environment.
https://hub.docker.com/r/rundeck/rundeck/

I see that  documents of this plugin don't mention about python.

It might be better to write about the need for python.

**Comment by ltamaster** [comment]
Hi @endu 

You can extend the official image, for example: https://github.com/rundeck/docker-zoo/tree/master/config

Luis

**Comment by endu** [comment]
Thank you for an answer.
You're right. I decided to install the python environment myself.
