### ISSUE TITLE
Does not build with gradle 5+

### ISSUE THREAD

**Issue by dmarteau** [rundeck-plugins/docker#45]
Building  master give the following error: 
```
FAILURE: Build failed with an exception.

* Where:
Script 'https://raw.githubusercontent.com/rundeck-plugins/build-zip/master/build.gradle' line: 74

* What went wrong:
A problem occurred evaluating script.
> Could not find method leftShift() for arguments [build_5euplq0w1agkutluqphlqsf3j$_run_closure4@cf77c5b] on task ':build' of type org.gradle.api.DefaultTask.
```

Possible cause:
```
<< was deprecated in Gradle 4.x and removed in Gradle 5.0
```

See discussion: https://discuss.gradle.org/t/could-not-find-method-leftshift-for-arguments-on-task-of-type-org-gradle-api-defaulttask/30614

**Comment by ltamaster** [comment]
did you try with `gradlew` ? 
Luis

**Comment by dmarteau** [comment]
> did you try with `gradlew` ?
> Luis

gradlew does not address this issue: it is matter of Gradle version.

**Comment by ltamaster** [comment]
Hi @dmarteau 
The dependency uses gradle 4.7, I understand gradlew should download the 4.7 version.
I that still failing for you?

**Comment by dmarteau** [comment]
Hi,

I suceeded building the plugins with gradle 4.10.2 into the rundeck docker image (which is based on an Ubuntu/Xenial image)

But the story is that  the actual gradle version which is installed from https://get.sdkman.io is the version 5.7+.  I am suggesting that it may be relevant to upgrade the installation script so that it supports an up to date gradle version.

**Comment by Geraldf** [comment]
I was successf in building it with gradle version 6.5.1 by doing the following steps. 

- look at your current "build.gradle" file.  
- the last line is: "apply from: 'https://raw.githubusercontent.com/rundeck-plugins/build-zip/master/build.gradle'"
- download that file locally and name it to "whatever.gradle"
- change the last line of your build.gradle to: apply from: 'whatever.gradle'
- open the "whatever.gradle" and replace the `"<<"` with `"doLast"`  (Line 74 and 77) 

then the build worked for me.

**Comment by fdevans** [comment]
Builds seem to succeed now.  Please reopen if it's still an issue
